apiVersion: v1
kind: Service
metadata:
  name: kk-payments
  namespace: kijani-project

spec:
  type: ClusterIP

  selector:
    app: kk-payments

  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP