apiVersion: v1
data:
  APP_PORT: "3001"
  DB_HOST: kk-payments-db
  DB_PORT: "5432"
  LOG_LEVEL: info
  MAX_CONNECTIONS: "10"
  NODE_ENV: development
  RECEIPTS_BUCKET: kijani-payments-receipts-dev
  AWS_REGION: af-south-1
kind: ConfigMap
metadata:
  name: kk-payments-config
  namespace: kijani-project