apiVersion: apps/v1
kind: Deployment
metadata:
  name: kk-payments
spec:
  replicas: 2

  selector:
    matchLabels:
      app: kk-payments

  template:
    metadata:
      labels:
        app: kk-payments

    spec:
      imagePullSecrets:
        - name: kijani-registry-credentials

      containers:
        - name: kk-payments
          image: host.minikube.internal:8082/docker-hosted/kijanikiosk-production:1.0.0-0685136

          ports:
            - containerPort: 3000

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

          env:
            - name: NODE_ENV
              value: "production"

          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10