apiVersion: v1
kind: Service
metadata:
  name: kk-payments-service
spec:
  type: NodePort
  selector:
    app: kk-payments
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
      nodePort: 30001
